owner: teslamint
repo: status.teslam.in

sites:
  - name: teslam.in
    url: https://teslam.in
  - name: teslam.in API
    url: https://teslam.in/api/v1/pleroma/healthcheck

status-website:
  cname: status.teslam.in
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: teslam.in Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
